### ISSUE TITLE
Programatically add /ai4eutils and /camertraps to user's PYTHONPATH

### ISSUE THREAD

**Issue by dddjjjbbb** [dddjjjbbb/Grunz#1]
As we're importing this code as a submodule in main, we are running into import errors without first modifying paths in the two respective submodules. Fortunately it should easily be solved by programmatically adding these two directories to the end user's PYTHONPATH at runtime. Without doing so this issue will re occur every time we pull from upstream.

**Comment by robinsandfort** [comment]
Hi, I changed the three "from cameratraps.ct_utils import truncate_float import cameratraps.visualization.visualization_utils as viz_utils" but still run into ModuleNotFoundError: No module named "tensorslow". I run tensorflow 1.15.0 on a raspberry.
Cheers Robin

**Comment by dddjjjbbb** [comment]
Hi @robinsandfort, thanks for this. If you could send me the full stack trace I can better understand what's failing your side. Thanks :)

**Comment by robinsandfort** [comment]
python main.py --pre "grunz/data"
Traceback (most recent call last):
  File "main.py", line 8, in <module>
    from cameratraps.detection.run_tf_detector_batch import (
  File "/home/pi/tf_cam/Grunz/cameratraps/detection/run_tf_detector_batch.py", line 49, in <module>
    from cameratraps.detection.run_tf_detector import ImagePathUtils, TFDetector
  File "/home/pi/tf_cam/Grunz/cameratraps/detection/run_tf_detector.py", line 67, in <module>
    import tensorflow as tf
ModuleNotFoundError: No module named 'tensorflow'

**Comment by dddjjjbbb** [comment]
Closing — this was resolved by the migration from cameratraps/ai4eutils to PytorchWildlife. Neither submodule exists in the project anymore, so the PYTHONPATH issue no longer applies.
