### ISSUE TITLE
Can't run "python main.py --post ...." command

### ISSUE THREAD

**Issue by ghost** [dddjjjbbb/Grunz#4]
Hi there,

I tried to run the "python main.py --post ..." command to post process the resultant JSON file but I keep on receiving this error:

-------------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "main.py", line 113, in <module>
    main()
  File "main.py", line 109, in main
    args = parser.parse_args()
  File ".../Grunz/lib/python3.7/argparse.py", line 1755, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File ".../Grunz/lib/python3.7/argparse.py", line 1787, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File ".../Grunz/lib/python3.7/argparse.py", line 1993, in _parse_known_args
    start_index = consume_optional(start_index)
  File ".../Grunz/lib/python3.7/argparse.py", line 1933, in consume_optional
    take_action(action, args, option_string)
  File ".../Grunz/lib/python3.7/argparse.py", line 1845, in take_action
    argument_values = self._get_values(action, argument_strings)
  File ".../Grunz/lib/python3.7/argparse.py", line 2376, in _get_values
    value = self._get_value(action, arg_string)
  File ".../Grunz/lib/python3.7/argparse.py", line 2409, in _get_value
    result = type_func(arg_string)
  File "main.py", line 77, in post_pro
    positive_avi_paths = json_parser.get_list_for_sort(positive_jpeg_file_paths)
  File ".../Grunz/grunz/json_parser/json_parser.py", line 115, in get_list_for_sort
    return [JSONParser.__convert_jpeg_path_to_original_avi(p) for p in jpeg_paths]
  File ".../Grunz/grunz/json_parser/json_parser.py", line 115, in <listcomp>
    return [JSONParser.__convert_jpeg_path_to_original_avi(p) for p in jpeg_paths]
  File "..../Grunz/grunz/json_parser/json_parser.py", line 106, in __convert_jpeg_path_to_original_avi
    avi_path = re.search(r"PICT\d*\*\.AVI", jpeg_path).group(1)
AttributeError: 'NoneType' object has no attribute 'group'

-------------------------------------------------------------------------------------------------------

Does someone know how to fix this ? I  appreciate your help in advance

**Comment by dddjjjbbb** [comment]
Closing — this was fixed in the codebase refactor. The regex is now corrected, the None case raises a clear ValueError, and there's a regression test covering it in test_path_safety.py.
